  uuid1:
    required:
     - uuid
    properties:
      uuid:
        type: "string"
        format: "uuid"
      node:
        type: "integer"
        format: "int64"
      time:
        type: "integer"
        format: "int64"
    externalDocs:
      url: "https://docs.python.org/3/library/uuid.html"
    example:
      uuid: "0729a580-2240-11e6-9eb5-0002a5d5c51b"
      type: "led"
      id: "1"
